### ISSUE TITLE
No xdg-open command on Mac

### ISSUE THREAD

**Issue by realhackcraft** [Aliqyan-21/wit.nvim#2]
On MacOS, there is no xdg-open command.

There is a similar command, `open`.

Can you detect if the user is using MacOS, and run open instead?

Running `open https://google.com` results in the browser opening to google and doesn't output any text.

If you don't have time, I could try fixing this and submit a pr in a few days.

**Comment by Aliqyan-21** [comment]
Hey yes that's a great idea I would like if you contribute...

I think we can use this method of finding out the uname, from reading the file handle output.

###### As uname for macos is Darwin and for Linux is Linux

```lua
local os_name

local fh = io.popen("uname")
local uname = fh:read("*l")
fh:close()
if uname == "Darwin" then
	os_name = "MacOS"
else
	os_name = "Linux"
end

print(os_name)
```

Try this code in your macos and see if it outputs MacOS...

or we can use the package.cpath method to detect the os, I saw it on stackoverflow.

Please go ahead and add macos support.

**Comment by realhackcraft** [comment]
I have create #3

**Comment by Aliqyan-21** [comment]
Yes It's great, Your PR has been merged. Thank you. And with this I am closing the issue
